$(function(){
	$(".loginTab").click(function(){
		$(this).siblings().removeClass("on");
		$(this).addClass("on");
		$(".loginFormDiv").show();
		$(".joinFormDiv").hide();
	});
	$(".joinTab").click(function(){
		$(this).siblings().removeClass("on");
		$(this).addClass("on");
		$(".loginFormDiv").hide();
		$(".joinFormDiv").show();
	});
	$(".studentTab").click(function(){
		$(this).siblings().removeClass("on");
		$(this).addClass("on");
		$(".teacherInfo").hide();
		$("input:hidden").val("학생");
	});
	$(".teacherTab").click(function(){
		$(this).siblings().removeClass("on");
		$(this).addClass("on");
		$(".teacherInfo").show();
		$("input:hidden").val("교사");
	});
});